// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyfmxpnbkxtulwldnmnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5Zm14cG5ia3h0dWx3bGRubW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNzI3OTcsImV4cCI6MjA1Njg0ODc5N30.EdnIhY0j1Bbol1awyl-oQDnI8mX6D5zxZKwzdvazMXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);